name: just_look_up
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  hexcolor: ^2.0.6
  isolated_worker: ^0.1.0
  confetti: ^0.6.0
  flutter_svg: ^1.0.3
  simple_shadow: ^0.3.0
  bloc: ^8.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/images/
  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Black.ttf
